added path to check filename

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -32,8 +32,12 @@ jobs:
     - name: Prepare Report for Upload
       run: |
         mkdir -p ./report-output
-        # Copy only the JSON report file generated by playwright-ctrf-json-reporter
-        cp ./playwright-report.json ./report-output/
+        if [ -f ./ctrf/playwright-report.json ]; then
+          cp ./ctrf/playwright-report.json ./report-output/
+        else
+          echo "Report file not found"
+          exit 1
+        fi
     - name: Install 7-Zip
       run: sudo apt-get install p7zip-full
     - name: Password protect playwright report
